name: "test-onnx-512"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [512, 2048, 1 ]
  }
]
output [
  {
    name: "dense_4"
    data_type: TYPE_FP32
    dims: [512, 2]
  }
]
instance_group [
  {
    count: 8
    kind: KIND_GPU
  }
]
#optimization { execution_accelerators {
#  gpu_execution_accelerator : [ {
#    name : "tensorrt"
#    parameters { key: "precision_mode" value: "FP32" }
#    parameters { key: "max_workspace_size_bytes" value: "1073741824" }
#    }]
#}}